#!/bin/bash
yes | apt-get update
yes | apt-get upgrade
for package_name in "$@"
do
yes | apt-get install $package_name
done
clear
#after adding to .bashrc in aliases file usage is simple: package <packagename> <packagename> to install packages, needs to be followed by sudo (security)
